# Forge System - Limine Bootloader Config
# https://github.com/limine-bootloader/limine

TIMEOUT=0

:Forge
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=ROOTUUID rw rootflags=subvol=@ quiet loglevel=0

    INITRD_PATH=boot:///initramfs-linux.img

    # Splash screen
    MODULE_PATH=boot:///boot/splash.bmp

:Forge (recovery)
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    CMDLINE=root=UUID=ROOTUUID rw rootflags=subvol=@ single

    INITRD_PATH=boot:///initramfs-linux.img
