#!/bin/bash
# Generate app and desktop data as QML-importable JavaScript

DATA_DIR="$HOME/.local/share/forge"
mkdir -p "$DATA_DIR"
JS_FILE="$DATA_DIR/data.js"

# Use python for proper JSON escaping
python3 -c "
import os, json

home = os.path.expanduser('~')
data_dir = os.path.join(home, '.local/share/forge')

# Wallpaper
wallpaper = ''
for p in [os.path.join(home, '.config/forge/wallpaper'),
          os.path.join(home, '.wallpaper'),
          os.path.join(home, 'Pictures/wallpaper.png'),
          os.path.join(home, 'Pictures/wallpaper.jpg'),
          os.path.join(home, '.config/hypr/wallpaper.jpg'),
          os.path.join(home, '.config/hypr/wallpaper.png')]:
    if os.path.isfile(p):
        wallpaper = p
        break

# Desktop files
desktop_files = []
desktop_dir = os.path.join(home, 'Desktop')
if os.path.isdir(desktop_dir):
    for f in sorted(os.listdir(desktop_dir)):
        path = os.path.join(desktop_dir, f)
        if os.path.isdir(path):
            desktop_files.append({'name': f, 'isDir': 1})
        elif os.path.isfile(path):
            desktop_files.append({'name': f, 'isDir': 0})

# App files
apps = []
apps_dir = '/usr/share/applications'
if os.path.isdir(apps_dir):
    for f in sorted(os.listdir(apps_dir)):
        if not f.endswith('.desktop'):
            continue
        path = os.path.join(apps_dir, f)
        if not os.path.isfile(path):
            continue

        name = icon_path = exec_cmd = ''
        with open(path, 'r', errors='ignore') as fh:
            for line in fh:
                if line.startswith('NoDisplay=true') or line.startswith('Hidden=true'):
                    name = ''
                    break
                if line.startswith('Name=') and not name:
                    name = line.strip().split('=', 1)[1]
                if line.startswith('Icon=') and not icon_path:
                    icon = line.strip().split('=', 1)[1]
                    if icon.startswith('/') and os.path.isfile(icon):
                        icon_path = icon
                    else:
                        for size in ['128x128', '96x96', '64x64', '48x48', '32x32']:
                            for d in [f'/usr/share/icons/hicolor/{size}/apps',
                                      '/usr/share/icons/hicolor/scalable/apps',
                                      '/usr/share/pixmaps']:
                                for ext in ['png', 'svg']:
                                    fp = os.path.join(d, f'{icon}.{ext}')
                                    if os.path.isfile(fp):
                                        icon_path = fp
                                        break
                                if icon_path:
                                    break
                                fp = os.path.join(d, icon)
                                if os.path.isfile(fp):
                                    icon_path = fp
                                    break
                            if icon_path:
                                break
                if line.startswith('Exec=') and not exec_cmd:
                    exec_cmd = line.strip().split('=', 1)[1]

        if name:
            apps.append({'name': name, 'iconPath': icon_path, 'exec': exec_cmd})

# Write JS
with open(os.path.join(data_dir, 'data.js'), 'w') as out:
    out.write('// Auto-generated by Forge\\n')
    out.write('.pragma library\\n\\n')
    out.write(f'var wallpaper = {json.dumps(wallpaper)}\\n\\n')
    out.write('var desktopFiles = ' + json.dumps(desktop_files, indent=2) + '\\n\\n')
    out.write('var apps = ' + json.dumps(apps, indent=2) + '\\n')

print(f'Generated {len(apps)} apps, {len(desktop_files)} desktop files')
" 2>&1

echo "Generated data.js"
